namespace: staging
images:
- name: bigkevmcd/go-demo
  newTag: demo
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- namespace.yaml
labels:
- includeSelectors: true
  pairs:
    gitops.pro/pipeline-environment: staging
