image: golang:latest
tekton:
  serviceAccountName: tekton-ci

before_script:
  - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.24.0

stages:
  - test
  - update-image

test-go:
  stage: test
  script:
    - go mod download
    - go fmt ./...
    - go vet ./...
    - ./bin/golangci-lint run
    - go test -race ./...

build-image:
  stage: update-image
  rules:
    - if: vars.CI_COMMIT_BRANCH != 'master'
      when: never
  tekton:
    taskRef: buildah
    params:
     - name: IMAGE
       expr: "'quay.io/bigkevmcd/go-demo:master-' + vars.CI_COMMIT_SHORT_SHA"
