resources:
- ../../base
- namespace.yaml
namespace: production
images:
- name:  bigkevmcd/go-demo
  newTag: '20211007085415'
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: go-demo-http
  path: go_demo_patch.yaml
