resources:
- ../../base
- namespace.yaml
namespace: production
images:
- name: bigkevmcd/go-demo
  newTag: "20211007085415"
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: go_demo_patch.yaml
  target:
    group: apps
    kind: Deployment
    name: go-demo-http
    version: v1
