apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-http
  labels:
    app.kubernetes.io/name: go-demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: go-demo
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-demo
    spec:
      containers:
      - name: http
        image: docker.io/bigkevmcd/go-demo:876ecb3
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: go-demo-config
