resources:
- deployment.yaml
- service.yaml
- configMap.yaml
- redis_service.yaml
- redis_deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: go-demo
