apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-http
  labels:
    app.kubernetes.io/name: go-demo
    app.kubernetes.io/part-of: go-demo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: go-demo
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: go-demo
    spec:
      containers:
      - name: http
        image: bigkevmcd/go-demo:latest
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_URL
          value: redis://redis:6379/0
---
apiVersion: v1
kind: Service
metadata:
  name: go-demo-http
  labels:
    app.kubernetes.io/name: go-demo
spec:
  ports:
  - port: 8080
  selector:
    app.kubernetes.io/name: go-demo
